# Generated by Django 5.1.3 on 2024-11-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('Address', models.CharField(max_length=80)),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
